// Package docs holds the generated Swagger/OpenAPI documentation.
// This file is auto-generated by swaggo/swag and should not be edited manually.
// Run: cd backend && swag init -g cmd/api/main.go --output docs
//
// For now this is a placeholder that registers empty docs so the binary compiles.
// Run `swag init` to regenerate after adding handler annotations.
package docs
